name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build App
        run: |
          # 1. Cordova इंस्टॉल करें
          npm install -g cordova
          
          # 2. एकदम फ्रेश प्रोजेक्ट बनाएँ
          cordova create myApp com.sst.pro "SSTPro"
          cd myApp
          
          # 3. डिफ़ॉल्ट फाइलों को अपनी फाइलों से बदलें
          rm www/index.html
          cp ../index.html www/
          
          # 4. Android जोड़ें और बिल्ड करें (Stable Version)
          cordova platform add android@10.1.2
          cordova build android --no-telemetry --device

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sst-pro-app-apk
          path: myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
